create table users(
      username varchar_ignorecase(50) not null primary key,
      password varchar_ignorecase(50) not null,
      api_token varchar(64) not null);

create unique index ix_users_api_token on users(api_token);

create table followers (
    id bigint generated by default as identity(start with 0) primary key,
    username varchar_ignorecase(50) not null,
    following varchar_ignorecase(50) not null,
    constraint fk_source_users foreign key(username) references users(username),
    constraint fk_target_users foreign key(following) references users(username));

create unique index ix_followers_username_following on followers(username,following);

create table messages (
    id bigint generated by default as identity(start with 0) primary key,
    author varchar_ignorecase(50) not null,
    text varchar(160) not null,
    creation_time bigint not null,
    constraint fk_author_messages_users foreign key(author) references users(username));

